name: ci
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm i
      - name: Build packages
        run: |
          npm -w @prismix/core run build
          npm -w @prismix/cli run build
      - name: Generate example
        run: npm run generate
      - name: Upload generated artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated
          path: examples/blog/generated
