name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Show versions
        run: |
          node -v
          npm -v

      - name: Install
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      # If dist/ is NOT committed, uncomment this and ensure "npm run build" exists:
      # - name: Build
      #   run: npm run build

      - name: Generate code
        run: npm run generate

      - name: Upload generated outputs
        uses: actions/upload-artifact@v4
        with:
          name: prismix-generated
          path: |
            examples/**/generated/**
          if-no-files-found: ignore
